Repository srivastavaritik/Extraspace-Cloud, pull requests merged in 2023-05, with the labels that each got.

#61 Page Not Found Completed
  src/components/App.js
  src/components/authentication/PageNotFound.js
  src/components/authentication/css/NotFound.css
Labels: gssoc23, level2

#98 Fixed : issue#60
  README.md
Labels: gssoc23, gssoc23-accepted, level1

#80 validation of password strength ::issue #57
  src/components/authentication/Signup.js
  yarn.lock
Labels: gssoc23, level2, gssoc23-accepted

#116 Added {"> "} in Files and Links, and removed unwanted styles
  public/index.html
  src/components/drive/Dashboard.js
  src/components/drive/FolderBreadcrums.css
Labels: gssoc23, gssoc23-accepted, level3
